export const REQUEST_SAVED_ARTICLES = 'REQUEST_SAVED_ARTICLES';
export const RECEIVE_SAVED_ARTICLES = 'RECEIVE_SAVED_ARTICLES';
export const RECEIVE_SAVED_ARTICLES_FAILURE = 'RECEIVE_SAVED_ARTICLES_FAILURE';

export const BEGIN_REMOVE_SAVED_ARTICLE = 'BEGIN_REMOVE_SAVED_ARTICLE';
export const SUCCESS_REMOVE_SAVED_ARTICLE = 'SUCCESS_REMOVE_SAVED_ARTICLE';
export const FAILURE_REMOVE_SAVED_ARTICLE = 'FAILURE_REMOVE_SAVED_ARTICLE';